[package]
name = "varisat"
version = "0.2.0"
authors = ["Jannis Harder <me@jix.one>"]
build = "build.rs"
edition = "2018"

[dependencies]
bincode = "1.1.2"
failure = "0.1.3"
itoa = "0.4.3"
log = "0.4.6"
ordered-float = "1.0.1"
partial_ref = "0.3.0"
serde = { version = "1.0.89", features = ["derive"] }
leb128 = "0.2.3"
hashbrown = "0.1.8"
smallvec = "0.6.9"

[dev-dependencies]
proptest = "0.9.1"
rand = "0.6.5"
tempfile = "3.0.7"

[build-dependencies]
failure = "0.1.3"
