[package]
name = "varisat"
version = "0.2.0"
authors = ["Jannis Harder <me@jix.one>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
itoa = "0.4.3"
partial_ref = "0.1.2"

[dev-dependencies]
proptest = "0.9.1"
rand = "0.6.5"
