language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo doc --document-private-items --no-deps

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      curl -Ls 'https://gist.github.com/jix/4342dd522a7125a2803c6edeedd8735c/raw' > $HOME/.cargo/bin/rustc-proptest-fix
      chmod 755 $HOME/.cargo/bin/rustc-proptest-fix

      # While this not recommended anymore, the version mismatch shouldn't cause problems here.
      bash <(curl -sL https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)

      RUSTC=rustc-proptest-fix cargo tarpaulin --ignore-tests --out Xml
      bash <(curl -s https://codecov.io/bash)
  fi

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: target/doc
  github-token: $GITHUB_TOKEN
  on:
    branch: master
    rust: nightly # Change to stable when intra rustdoc links landed
