[workspace]
members = [
    "varisat",
]

[profile.dev]
opt-level = 1

[profile.test]
opt-level = 1

[profile.release]
debug = true # Enables profiling

[profile.bench]
debug = true # Enables profiling
