[package]
name = "varisat-formula"
version = "0.2.2"
authors = ["Jannis Harder <me@jix.one>"]
edition = "2018"
description = "Basic formula data types used by the Varisat SAT solver"
homepage = "https://jix.one/project/varisat/"
repository = "https://github.com/jix/varisat"
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
default = []
proptest-strategies = ["proptest"]
internal-testing = ["proptest", "rand"]

[dependencies]
proptest = { version = "0.10.1", optional = true }
rand = { version = "0.7.3", optional = true }
profiling = { git="https://github.com/AstroOrbis/profiling"}
itertools = { git="https://github.com/AstroOrbis/itertools", branch = "profiling"}
rayon = "1.10.0"

[[bench]]
name = "exactly_one"
harness = false

[dev-dependencies]
proptest = "0.10.1"
rand = "0.7.3"
criterion = "0.6.0"